name: scipy-2022-jupyterlite-poster

channels:
  - conda-forge

dependencies:
  - mamba
  - pydata-sphinx-theme
  - empack

  - pip:
    - jupyterlite-sphinx
    - jupyterlite-xeus-python>=0.5
    - -r ../requirements.txt